plugins {
    id 'com.android.application'
}

android {
    namespace 'com.garrett.appvolumestepper'
    compileSdk 35

    defaultConfig {
        applicationId 'com.garrett.appvolumestepper'
        minSdk 33
        targetSdk 35
        versionCode 10
        versionName '1.9'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
    implementation 'org.lsposed.hiddenapibypass:hiddenapibypass:6.1'
    implementation 'org.jooq:joor:0.9.15'
}
